// <auto-generated />
using lab6.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace lab6.Migrations
{
    [DbContext(typeof(UchetDbContext))]
    partial class UchetDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("lab6.Models.Brand", b =>
                {
                    b.Property<int>("BrandID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("BrandCompany");

                    b.Property<string>("BrandCountry");

                    b.Property<string>("BrandName");

                    b.HasKey("BrandID");

                    b.ToTable("Brands");
                });

            modelBuilder.Entity("lab6.Models.Car", b =>
                {
                    b.Property<int>("CarID")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("BrandID");

                    b.Property<string>("CarColor");

                    b.Property<string>("CarNumberOfPassport");

                    b.Property<string>("CarRegistrationNumber");

                    b.Property<DateTime?>("CarReleaseDate");

                    b.Property<int?>("OwnerID");

                    b.HasKey("CarID");

                    b.HasIndex("BrandID");

                    b.HasIndex("OwnerID");

                    b.ToTable("Cars");
                });

            modelBuilder.Entity("lab6.Models.Owner", b =>
                {
                    b.Property<int>("OwnerID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("OwnerAddress");

                    b.Property<DateTime?>("OwnerBirthDate");

                    b.Property<string>("OwnerName");

                    b.HasKey("OwnerID");

                    b.ToTable("Owners");
                });

            modelBuilder.Entity("lab6.Models.Car", b =>
                {
                    b.HasOne("lab6.Models.Brand", "Brand")
                        .WithMany("Cars")
                        .HasForeignKey("BrandID");

                    b.HasOne("lab6.Models.Owner", "Owner")
                        .WithMany("Cars")
                        .HasForeignKey("OwnerID");
                });
#pragma warning restore 612, 618
        }
    }
}
